# Generated by Django 3.2 on 2021-09-16 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(null=True, verbose_name='Salary')),
                ('occupation', models.CharField(max_length=250, null=True, verbose_name='Occupation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
