# Generated by Django 3.2 on 2021-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_profile', '0002_auto_20211014_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='country',
            field=models.CharField(max_length=250, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='passport',
            field=models.CharField(max_length=250, null=True, verbose_name='Passport'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='ssn',
            field=models.CharField(max_length=250, null=True, verbose_name='Last 4 nums of SSN / ITIN'),
        ),
    ]
