# Generated by Django 3.2 on 2021-08-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_rename_guide_simple_form_guidestaticpagelistwithicons_guide_static_page'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guidesimpleformchoices',
            unique_together={('guide_simple_form', 'sort_index')},
        ),
        migrations.AlterUniqueTogether(
            name='guidestaticpagelistwithicons',
            unique_together={('guide_static_page', 'sort_index')},
        ),
    ]
