# Generated by Django 3.2 on 2021-08-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20210830_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='sort_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='guidemodule',
            name='sort_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='guidesimpleformchoices',
            name='sort_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='guidestaticpagelistwithicons',
            name='sort_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='guidestep',
            name='sort_index',
            field=models.PositiveIntegerField(),
        ),
    ]
