# Generated by Django 3.2 on 2021-09-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20210830_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestep',
            name='content_type',
            field=models.CharField(choices=[('static_page', 'Static pages'), ('simple_choice_form', 'Simple choice form'), ('multiple_choice_form', 'Multiple choice form'), ('custom', 'Custom content')], default='static_page', max_length=100),
        ),
        migrations.CreateModel(
            name='GuideMultiChoiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Form title for guide multi choice form', max_length=250)),
                ('guide_step', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multi_choice_form', to='guides.guidestep')),
            ],
        ),
        migrations.CreateModel(
            name='GuideMultiChoiceFormChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.PositiveIntegerField()),
                ('text', models.CharField(help_text='Choices for guide multi choices form', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image for guide multi choices form')),
                ('guide_multi_choices_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guides.guidemultichoiceform')),
            ],
            options={
                'ordering': ['sort_index', 'id'],
                'unique_together': {('guide_multi_choices_form', 'sort_index')},
            },
        ),
    ]
