# Generated by Django 3.2 on 2021-09-14 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0005_auto_20210914_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuideMultiChoiceFormChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_form_item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.guidemultichoiceformchoices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
