# Generated by Django 3.2 on 2021-09-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_userguidemultichoiceformchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userguidemultichoiceformchoice',
            old_name='simple_form_item_id',
            new_name='multi_choice_form_item_id',
        ),
    ]
