# Generated by Django 3.2 on 2021-10-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_guide_guide_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['sort_index', 'guide_type']},
        ),
    ]
