/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomUserDetails
 */
export interface CustomUserDetails {
    /**
     * 
     * @type {string}
     * @memberof CustomUserDetails
     */
    readonly opk?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof CustomUserDetails
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CustomUserDetails
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomUserDetails
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomUserDetails
     */
    lastName?: string;
}

export function CustomUserDetailsFromJSON(json: any): CustomUserDetails {
    return CustomUserDetailsFromJSONTyped(json, false);
}

export function CustomUserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomUserDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'opk': !exists(json, 'opk') ? undefined : json['opk'],
        'username': json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function CustomUserDetailsToJSON(value?: CustomUserDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

