/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialProfile
 */
export interface FinancialProfile {
    /**
     * 
     * @type {number}
     * @memberof FinancialProfile
     */
    salary?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialProfile
     */
    occupation?: string | null;
    /**
     * How long have you lived in the U.S.?
     * @type {string}
     * @memberof FinancialProfile
     */
    liveInUs?: string | null;
    /**
     * What is your residence status in the U.S.?
     * @type {string}
     * @memberof FinancialProfile
     */
    residenceStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialProfile
     */
    ssn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialProfile
     */
    passport?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialProfile
     */
    country?: string | null;
}

export function FinancialProfileFromJSON(json: any): FinancialProfile {
    return FinancialProfileFromJSONTyped(json, false);
}

export function FinancialProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'salary': !exists(json, 'salary') ? undefined : json['salary'],
        'occupation': !exists(json, 'occupation') ? undefined : json['occupation'],
        'liveInUs': !exists(json, 'live_in_us') ? undefined : json['live_in_us'],
        'residenceStatus': !exists(json, 'residence_status') ? undefined : json['residence_status'],
        'ssn': !exists(json, 'ssn') ? undefined : json['ssn'],
        'passport': !exists(json, 'passport') ? undefined : json['passport'],
        'country': !exists(json, 'country') ? undefined : json['country'],
    };
}

export function FinancialProfileToJSON(value?: FinancialProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'salary': value.salary,
        'occupation': value.occupation,
        'live_in_us': value.liveInUs,
        'residence_status': value.residenceStatus,
        'ssn': value.ssn,
        'passport': value.passport,
        'country': value.country,
    };
}

