/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GuideModuleSteps,
    GuideModuleStepsFromJSON,
    GuideModuleStepsFromJSONTyped,
    GuideModuleStepsToJSON,
} from './';

/**
 * 
 * @export
 * @interface GuideModule
 */
export interface GuideModule {
    /**
     * 
     * @type {number}
     * @memberof GuideModule
     */
    readonly id?: number;
    /**
     * Appears as the title for this guide module
     * @type {string}
     * @memberof GuideModule
     */
    title: string;
    /**
     * Used by the clients to lookup specific guide modules.
     * @type {string}
     * @memberof GuideModule
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof GuideModule
     */
    sortIndex: number;
    /**
     * 
     * @type {Array<GuideModuleSteps>}
     * @memberof GuideModule
     */
    steps: Array<GuideModuleSteps>;
}

export function GuideModuleFromJSON(json: any): GuideModule {
    return GuideModuleFromJSONTyped(json, false);
}

export function GuideModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuideModule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': json['title'],
        'slug': json['slug'],
        'sortIndex': json['sort_index'],
        'steps': ((json['steps'] as Array<any>).map(GuideModuleStepsFromJSON)),
    };
}

export function GuideModuleToJSON(value?: GuideModule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'slug': value.slug,
        'sort_index': value.sortIndex,
        'steps': ((value.steps as Array<any>).map(GuideModuleStepsToJSON)),
    };
}

