/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuideModuleContentOptions
 */
export interface GuideModuleContentOptions {
    /**
     * 
     * @type {number}
     * @memberof GuideModuleContentOptions
     */
    readonly id?: number;
    /**
     * Option for static page list with icons.
     * @type {string}
     * @memberof GuideModuleContentOptions
     */
    text: string;
    /**
     * 
     * @type {Blob}
     * @memberof GuideModuleContentOptions
     */
    image?: Blob | null;
    /**
     * 
     * @type {number}
     * @memberof GuideModuleContentOptions
     */
    sortIndex: number;
}

export function GuideModuleContentOptionsFromJSON(json: any): GuideModuleContentOptions {
    return GuideModuleContentOptionsFromJSONTyped(json, false);
}

export function GuideModuleContentOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuideModuleContentOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'text': json['text'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'sortIndex': json['sort_index'],
    };
}

export function GuideModuleContentOptionsToJSON(value?: GuideModuleContentOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'image': value.image,
        'sort_index': value.sortIndex,
    };
}

