/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuideGuideModuleRead
 */
export interface GuideGuideModuleRead {
    /**
     * 
     * @type {number}
     * @memberof GuideGuideModuleRead
     */
    guideModule?: number | null;
}

export function GuideGuideModuleReadFromJSON(json: any): GuideGuideModuleRead {
    return GuideGuideModuleReadFromJSONTyped(json, false);
}

export function GuideGuideModuleReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuideGuideModuleRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guideModule': !exists(json, 'guide_module') ? undefined : json['guide_module'],
    };
}

export function GuideGuideModuleReadToJSON(value?: GuideGuideModuleRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guide_module': value.guideModule,
    };
}

