/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuideModuleContentItems
 */
export interface GuideModuleContentItems {
    /**
     * 
     * @type {number}
     * @memberof GuideModuleContentItems
     */
    readonly id?: number;
    /**
     * Choices for guide simple form
     * @type {string}
     * @memberof GuideModuleContentItems
     */
    text: string;
    /**
     * 
     * @type {Blob}
     * @memberof GuideModuleContentItems
     */
    image?: Blob | null;
}

export function GuideModuleContentItemsFromJSON(json: any): GuideModuleContentItems {
    return GuideModuleContentItemsFromJSONTyped(json, false);
}

export function GuideModuleContentItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuideModuleContentItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'text': json['text'],
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function GuideModuleContentItemsToJSON(value?: GuideModuleContentItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'image': value.image,
    };
}

