/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JWTUser
 */
export interface JWTUser {
    /**
     * 
     * @type {number}
     * @memberof JWTUser
     */
    readonly pk?: number;
    /**
     * 
     * @type {string}
     * @memberof JWTUser
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof JWTUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof JWTUser
     */
    lastName?: string;
}

export function JWTUserFromJSON(json: any): JWTUser {
    return JWTUserFromJSONTyped(json, false);
}

export function JWTUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): JWTUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pk': !exists(json, 'pk') ? undefined : json['pk'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function JWTUserToJSON(value?: JWTUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

