/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * 
     * @type {boolean}
     * @memberof Offer
     */
    recommended?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Offer
     */
    ssnRequired?: boolean;
    /**
     * 
     * @type {object}
     * @memberof Offer
     */
    pros?: object;
    /**
     * 
     * @type {object}
     * @memberof Offer
     */
    prosShort?: object;
    /**
     * 
     * @type {object}
     * @memberof Offer
     */
    cons: object;
    /**
     * 
     * @type {number}
     * @memberof Offer
     */
    reviewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Offer
     */
    reviewStars?: number;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    shortTitle: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    longTitle: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    ctaText: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    ctaAction: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    readonly ctaUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    category: OfferCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    recipientGets?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    totalCost?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Offer
     */
    isVerified?: boolean;
    /**
     * 
     * @type {Blob}
     * @memberof Offer
     */
    logo?: Blob | null;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    learnMore?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum OfferCategoryEnum {
    MoneyTransfer = 'money-transfer',
    StudentLoans = 'student-loans',
    CreditBuildingCards = 'credit-building-cards',
    CreditCards = 'credit-cards',
    CreditBuilder = 'credit-builder',
    Banking = 'banking'
}

export function OfferFromJSON(json: any): Offer {
    return OfferFromJSONTyped(json, false);
}

export function OfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Offer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recommended': !exists(json, 'recommended') ? undefined : json['recommended'],
        'ssnRequired': !exists(json, 'ssn_required') ? undefined : json['ssn_required'],
        'pros': !exists(json, 'pros') ? undefined : json['pros'],
        'prosShort': !exists(json, 'pros_short') ? undefined : json['pros_short'],
        'cons': json['cons'],
        'reviewCount': !exists(json, 'review_count') ? undefined : json['review_count'],
        'reviewStars': !exists(json, 'review_stars') ? undefined : json['review_stars'],
        'shortTitle': json['short_title'],
        'longTitle': json['long_title'],
        'ctaText': json['cta_text'],
        'ctaAction': json['cta_action'],
        'ctaUrl': !exists(json, 'cta_url') ? undefined : json['cta_url'],
        'category': json['category'],
        'recipientGets': !exists(json, 'recipient_gets') ? undefined : json['recipient_gets'],
        'totalCost': !exists(json, 'total_cost') ? undefined : json['total_cost'],
        'isVerified': !exists(json, 'is_verified') ? undefined : json['is_verified'],
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'learnMore': !exists(json, 'learn_more') ? undefined : json['learn_more'],
    };
}

export function OfferToJSON(value?: Offer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recommended': value.recommended,
        'ssn_required': value.ssnRequired,
        'pros': value.pros,
        'pros_short': value.prosShort,
        'cons': value.cons,
        'review_count': value.reviewCount,
        'review_stars': value.reviewStars,
        'short_title': value.shortTitle,
        'long_title': value.longTitle,
        'cta_text': value.ctaText,
        'cta_action': value.ctaAction,
        'category': value.category,
        'recipient_gets': value.recipientGets,
        'total_cost': value.totalCost,
        'is_verified': value.isVerified,
        'logo': value.logo,
        'learn_more': value.learnMore,
    };
}

