/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserGuideSimpleFormChoice
 */
export interface UserGuideSimpleFormChoice {
    /**
     * 
     * @type {number}
     * @memberof UserGuideSimpleFormChoice
     */
    simpleFormItemId: number;
}

export function UserGuideSimpleFormChoiceFromJSON(json: any): UserGuideSimpleFormChoice {
    return UserGuideSimpleFormChoiceFromJSONTyped(json, false);
}

export function UserGuideSimpleFormChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGuideSimpleFormChoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'simpleFormItemId': json['simple_form_item_id'],
    };
}

export function UserGuideSimpleFormChoiceToJSON(value?: UserGuideSimpleFormChoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'simple_form_item_id': value.simpleFormItemId,
    };
}

