/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserGuideMultiChoiceFormItems
 */
export interface UserGuideMultiChoiceFormItems {
    /**
     * 
     * @type {Array<any>}
     * @memberof UserGuideMultiChoiceFormItems
     */
    multiChoiceFormItemIds: Array<any>;
}

export function UserGuideMultiChoiceFormItemsFromJSON(json: any): UserGuideMultiChoiceFormItems {
    return UserGuideMultiChoiceFormItemsFromJSONTyped(json, false);
}

export function UserGuideMultiChoiceFormItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGuideMultiChoiceFormItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'multiChoiceFormItemIds': json['multi_choice_form_item_ids'],
    };
}

export function UserGuideMultiChoiceFormItemsToJSON(value?: UserGuideMultiChoiceFormItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'multi_choice_form_item_ids': value.multiChoiceFormItemIds,
    };
}

