# Generated by Django 3.2 on 2021-08-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralsTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=250, verbose_name='Partner')),
                ('offer_url', models.CharField(max_length=250, verbose_name='Offer Url')),
                ('offer_id', models.PositiveIntegerField(verbose_name='Offer Id')),
                ('offer_touchpoint', models.CharField(max_length=250, verbose_name='Offer Touchpoint')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passthroughs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
