# Generated by Django 3.2 on 2021-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralstracking',
            name='offer_id',
            field=models.CharField(max_length=250, verbose_name='Offer Id'),
        ),
    ]
