# Generated by Django 3.2 on 2021-09-03 18:42

from django.db import migrations, models
import django.db.models.deletion
import offers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Offer category.', max_length=250)),
                ('slug', models.SlugField(help_text='Used by the clients to lookup specific offers.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.PositiveIntegerField()),
                ('recommended', models.BooleanField(default=False)),
                ('ssn_required', models.BooleanField(default=False)),
                ('pros', models.JSONField(default=dict, validators=[offers.validators.validate_props])),
                ('pros_short', models.JSONField(default=dict, validators=[offers.validators.validate_props])),
                ('cons', models.JSONField(validators=[offers.validators.validate_props])),
                ('review_count', models.IntegerField(default=0)),
                ('review_stars', models.FloatField(default=0.0)),
                ('short_title', models.CharField(max_length=100)),
                ('long_title', models.CharField(max_length=250)),
                ('cta_text', models.CharField(max_length=50)),
                ('cta_action', models.URLField()),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='offers.offercategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
