# Generated by Django 3.2 on 2021-09-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['sort_index', 'id']},
        ),
    ]
