# Generated by Django 3.2 on 2021-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='partner_name',
            field=models.CharField(default='p_name', max_length=250),
            preserve_default=False,
        ),
    ]
