# Generated by Django 3.2 on 2021-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210915_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('money-transfer', 'Money transfer'), ('student-loans', 'Student loans'), ('credit-building-cards', 'Credit building cards'), ('credit-cards', 'Credit cards'), ('credit-builder', 'Credit builder'), ('banking', 'Banking')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('sort_index', 'category')},
        ),
    ]
