# Generated by Django 3.2 on 2021-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20210915_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='learn_more',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='logo',
            field=models.ImageField(null=True, upload_to='offers_logo'),
        ),
        migrations.AddField(
            model_name='offer',
            name='recipient_gets',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='total_cost',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
